#!/bin/bash
clear;echo "######################################"
echo -e "Auto installer Shadowsocks + ShadowsocksR\n######################################\n"
echo "Installing, Tunggu....."
mkdir -p /root/ss-ssr
url="https://github.com/Haris131/ss-ssr/raw/main"
wget -O /root/ss-ssr/shadowsocksr-libev_2018-03-07-d63ff863800a5645aca4309d5dd5962bd1e95543_aarch64_cortex-a53.ipk $url/shadowsocksr-libev_2018-03-07-d63ff863800a5645aca4309d5dd5962bd1e95543_aarch64_cortex-a53.ipk -q
wget -O /root/ss-ssr/luci-app-shadowsocksr_1.9.1-2_all.ipk $url/luci-app-shadowsocksr_1.9.1-2_all.ipk -q
opkg install /root/ss-ssr/*.ipk
rm -rf ss-ssr
echo -e "Shadowsocks + ShadowsocksR terinstall.\n\nSilahkan Akses via luci"
echo "Terima kasih -salam haris setyawan."
